name: Build and Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment'
        required: true
        type: choice
        options:
          - development
          - staging
          - production
      market:
        description: 'Select market'
        required: true
        type: choice
        options:
          - US
          - EU
          - APAC
      branch:
        description: 'Input branch to build image'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}

   
